version: 1.0.{build}

image: Visual Studio 2017

platform: x64

configuration: Release

shallow_clone: true
clone_depth: 5

matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

environment:
  matrix:
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

init:
  - ps: 'Write-Host "Building GEOS branch: $env:APPVEYOR_REPO_BRANCH" -ForegroundColor Magenta'
  #- ps: |
  #  Write-Host "Build worker environment variables:" -ForegroundColor Magenta
  #      Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}

install:
  - appveyor-retry appveyor DownloadFile https://cmake.org/files/v3.12/cmake-3.12.3-win64-x64.zip
  - 7z x cmake-3.12.3-win64-x64.zip -oC:\cmake > nul
  - set PATH=C:\cmake\bin;%PATH%
  - cmake --version

before_build:
  - ps: 'Write-Host "Running $env:BUILDER with $env:GENERATOR" -ForegroundColor Magenta'
  - if "%BUILDER%"=="CMake" cmake.exe -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: 'Write-Host "Running $env:BUILDER:" -ForegroundColor Magenta'
  - if "%BUILDER%"=="CMake" cmake --build . --config %CONFIGURATION%

test_script:
  - ps: 'Write-Host "Running tests:" -ForegroundColor Magenta'
  - if "%BUILDER%"=="CMake" ctest --output-on-failure -C %CONFIGURATION%

# If you need to debug AppVeyor session (https://www.appveyor.com/docs/how-to/rdp-to-build-worker), then:
# 1. Uncomment the on_finish section below:
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# 2. Add this line to the init section below
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
