# .travis.yml - Travis CI service configuration for GEOS
#
# This is free software; you can redistribute and/or modify it under
# the terms of the GNU Lesser General Public Licence as published
# by the Free Software Foundation.
# See the COPYING file for more information.
#
dist: trusty
sudo: false

language: cpp

ref:
  sources: &sources
    - ubuntu-toolchain-r-test

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources: *sources
          packages: ['g++-7']
      env:
        - E="CXX=g++-7 && ARCH=-m64 && CC=gcc-7"

    - os: linux
      addons:
        apt:
          sources: *sources
          packages: ['g++-4.8']
      env:
        - E="CXX=g++-4.8 && ARCH=-m64 && CC=gcc-4.8"

    - os: linux
      addons:
        apt:
          sources: *sources
          packages: ['clang-3.9']
      env:
        - E="CXX=clang++-3.9 && ARCH=-m64 && CC=clang-3.9"

    - os: linux
      addons:
        apt:
          sources: *sources
          packages: ['clang']
      env:
        - E="CXX=clang++ && ARCH=-m64 && CC=clang"

before_install:
  - eval "${E}"
  - export CXXFLAGS=${ARCH}
  - export CFLAGS=${ARCH}
  - export GEOS_BUILD_TOOL=cmake
  - ${CXX} --version

install:
  - which cmake
  - cmake --version
  - wget -O cmake-linux.sh https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh
  - sudo sh cmake-linux.sh -- --skip-license --prefix=/usr/local
  - export PATH=/usr/local/bin:$PATH
  - which cmake
  - cmake --version

script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/_build
  - mkdir -p ${TRAVIS_BUILD_DIR}/_install
  - cd ${TRAVIS_BUILD_DIR}/_build
  - cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/_install ${TRAVIS_BUILD_DIR}
  - cmake --build .
  - ctest --output-on-failure
  - cmake --build . --target install
  - mkdir -p ${TRAVIS_BUILD_DIR}/_build_client
  - cd ${TRAVIS_BUILD_DIR}/_build_client
  - cmake -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/_install -DCMAKE_VERBOSE_MAKEFILE=ON ${TRAVIS_BUILD_DIR}/examples/client
  - cmake --build .

notifications:
    irc:
        channels:
            - "chat.freenode.net#postgis-activity"
        on_success: always # [always|never|change] # default: change
        on_failure: always # [always|never|change] # default: always
        use_notice: false
    email:
        recipients:
            - geos-devel@lists.osgeo.org
        on_success: change
        on_failure: always
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/a38e35772d115f246fb9
        on_success: always  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: always    # options: [always|never|change] default: always
